# Generated by Django 4.0.6 on 2023-09-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
